### ISSUE TITLE
API - Optimization Backtesting

### ISSUE THREAD

**Issue by cvano** [rramboer/WolvWealth#14]

**Comment by rramboer** [comment]
Test quarterly, 15 year timespan

**Comment by rramboer** [comment]
Backtest functionality needs to be parametrizable in the following fields:
- Frequency of optimization (Daily, Weekly, Monthly, Quarterly) 
- Universe (top20, top50, top200)
- Maximum weight (per symbol)
- Maximum assets (total number of symbols in final portfolio)
