### ISSUE TITLE
API - Security - Authentication

### ISSUE THREAD

**Issue by cvano** [rramboer/WolvWealth#16]

**Comment by rramboer** [comment]
We are no longer using passwords for authentication. We should opt for another method of autheentication.

**Comment by rramboer** [comment]
Maybe JSON Web Tokens (JWT) or API keys?

**Comment by cvano** [comment]
This issue specifically refers to API Authentication, meaning authenticating API calls to ensure that Users are allowed to use the API.

Current plan is typical API token with limits on # calls per token.

**Comment by rramboer** [comment]
API Keys
Users (Username + Password)
