### ISSUE TITLE
DB - Migrate to NoSQL DB?

### ISSUE THREAD

**Issue by cvano** [rramboer/WolvWealth#18]
Need to research and consider performance. 

Might consider a cloud based solution like Google or AWS

-----------------------------------
| Data | Google | AWS |
| ------------- | ------------- | ------------- |
| Users |  | DocumentDB (w/ MongoDB) |
| Stock Data |  | DynamoDB (?) |
| Portfolios |  | DynamoDB or (maybe) S3 |
| Optimizations | ^ | ^ |
-----------------------------------

**Comment by rramboer** [comment]
No DB needed since data will be fetched and entered into CSV to be parsed as pandas DataFrame in real time

**Comment by cvano** [comment]
Reopening because DB is still necessary for authentication system in the future.

**Comment by cvano** [comment]
Closing this as we've concluded that we can stick with SQLite3 DB, will open new issue for the setup of that.
